name: Build and Deploy VitePress Docs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# 设置 GITHUB_TOKEN 的权限
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出代码
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      # 2. 安装 Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      # 3. 安装依赖
      - name: Install dependencies
        run: npm ci
      
      # 4. 构建 VitePress 文档
      - name: Build VitePress docs
        run: npm run docs:build
      
      # 5. 推送构建产物到 gh-pages 分支
      - name: Push to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          # 如果 GITHUB_TOKEN 权限不足，可以使用 personal_token
          #github_token: ${{ secrets.GITHUB_TOKEN }}
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: docs/.vitepress/dist
          publish_branch: gh-pages
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Build docs: ${{ github.sha }}'
          force_orphan: true